title: "Beatroot News: Text-only"
description: >- # this means to ignore newlines until "baseurl:"
  A plain-text version of Beatroot News.
baseurl: ""
url: "https://news.tatooine.club"
timezone: Asia/Kolkata